# UserBlock v1.0.0 Configs
# For Paper Server

main:
    # Enable: Do You Want To Enable Plugin To Work? (if false then plugin will not start)
    enable: true

    # Update Alert: Connect To Our API Server To Know When The Update Is Avirable And Warn You To Update When You Start The Server
    updatealert: true 

blocking:
    # Block Pattern: Block UserName By Pattern Example...
    # If You Use *Steve* It's Will Block "<something>Steve<something>"
    # But If You Use Steve* It's Will Block "Steve<something>"
    # But Will Not Block "<something>Steve<something>"
    # Others Example
    # If You Use ^Steve^ It's Will Block "Steve", "StEvE", "STEVE"
    # If You Use +Steve+ It's Will Block "S T E V E" (Filter SpaceBar)
    blockname:
    - ThisIsExampleYouCanRemoveMeOrReplaceMe

    # Block Pattern#2: Others Block Patterns Set (Will Tell What It Use Later)
    blockname2:
    - ThisIsExampleYouCanRemoveMeOrReplaceMe

    # AllowFloodgate: Floodgate Is The Bedrock Bridge That Make Bedrock Players Can Join Without Real Java Account
    # If Set To "true" Bedrock Via Floodgate Players Name Will Not Be Filtered By Block Pattern
    # But Will Use Block Pattern#2 To Filter Name Inserted
    allowfloodgate: false

otherssettings:
    # Others Setting Is Comming Soon